version: '3'

services:
  db:
    image: postgres:9.6.1
    volumes:
      - /var/lib/postgresql/data

  redis:
    image: redis:3.2.9-alpine

  web: &default
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - bundle:/bundle
    links:
      - db
      - redis
    depends_on:
      - db
      - redis
    command: ./bin/start.sh
    environment:
      - DATABASE_URL=postgres://postgres@db:5432
      - REDIS_URL=redis://redis:6379
      - BUNDLE_PATH=/bundle

  sidekiq:
    <<: *default
    command: bundle exec sidekiq -C config/sidekiq.yml -r .
    ports: []

volumes:
  bundle:
